version: "3.9"
services:
  postgres:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_PASSWORD: rust_rest
      POSTGRES_USER: rust_rest
      POSTGRES_DB: rust_rest
    ports:
      - 5432:5432
  postgres_test:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_PASSWORD: rust_rest_test
      POSTGRES_USER: rust_rest_test
      POSTGRES_DB: rust_rest_test
    ports:
      - 5433:5432
